/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Imagen;
import controller.Usuarios;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Vladimir Torres
 */
public class LoginTordavi extends javax.swing.JFrame {
          /**
           * Creates new form VentanaAdministradorTordavi
           */
          Usuarios users = new Usuarios();
          public LoginTordavi() {
                    initComponents();
                    this.setLocationRelativeTo(null);
                    labelIncorrecto.setVisible(false);
                    Imagen m = new Imagen(labelLogo,"src/images/logoTordavi.png");
                    Imagen close = new Imagen(lblClose,"src/images/icons/iconClose.png");
                    Imagen min = new Imagen(lblMinimizar,"src/images/icons/iconMinimizar.png");
          }
          public void validarLogin() {
                    if (txtUsuario.getText() != "" || txtPassword.getPassword().length != 0) {
                              String password = "";
                              for (int i = 0; i < txtPassword.getPassword().length; i++) {
                                        password += txtPassword.getPassword()[i];
                              }
                              if (users.login(txtUsuario.getText(), password)) {
                                        System.out.println("se inicio la sesión");
                                        VentanaAdministradorTordavi v = new VentanaAdministradorTordavi();
                                        v.setVisible(true);
                                        this.dispose();
                              } else {
                                        labelIncorrecto.setVisible(true);
                              }
                    } else {
                              labelIncorrecto.setText("No deje campos vacíos");
                              labelIncorrecto.setVisible(true);
                    }
          }

          /**
           * This method is called from within the constructor to initialize the
           * form. WARNING: Do NOT modify this code. The content of this method
           * is always regenerated by the Form Editor.
           */
          @SuppressWarnings("unchecked")
          // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
          private void initComponents() {

                    jPanel2 = new javax.swing.JPanel();
                    labelIncorrecto = new javax.swing.JLabel();
                    jPanel1 = new javax.swing.JPanel();
                    txtUsuario = new javax.swing.JTextField();
                    btnLogin = new javax.swing.JButton();
                    txtPassword = new javax.swing.JPasswordField();
                    jSeparator1 = new javax.swing.JSeparator();
                    jSeparator2 = new javax.swing.JSeparator();
                    labelLogo = new javax.swing.JLabel();
                    lblClose = new javax.swing.JLabel();
                    lblMinimizar = new javax.swing.JLabel();

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                    setBackground(new java.awt.Color(255, 255, 255));
                    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                    setUndecorated(true);
                    setResizable(false);
                    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                    jPanel2.setBackground(new java.awt.Color(0, 0, 0));

                    labelIncorrecto.setForeground(new java.awt.Color(255, 0, 0));
                    labelIncorrecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    labelIncorrecto.setText("Error al iniciar sesión");

                    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                    jPanel2.setLayout(jPanel2Layout);
                    jPanel2Layout.setHorizontalGroup(
                              jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addContainerGap(141, Short.MAX_VALUE)
                                        .addComponent(labelIncorrecto)
                                        .addGap(132, 132, 132))
                    );
                    jPanel2Layout.setVerticalGroup(
                              jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(labelIncorrecto)
                                        .addContainerGap(47, Short.MAX_VALUE))
                    );

                    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 374, -1));

                    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                    jPanel1.setForeground(new java.awt.Color(255, 255, 255));

                    txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
                    txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                    txtUsuario.setText("Usuario");
                    txtUsuario.setBorder(null);
                    txtUsuario.setSelectedTextColor(new java.awt.Color(255, 255, 255));
                    txtUsuario.setSelectionColor(new java.awt.Color(255, 255, 255));
                    txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        txtUsuarioMouseClicked(evt);
                              }
                    });
                    txtUsuario.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        txtUsuarioActionPerformed(evt);
                              }
                    });

                    btnLogin.setBackground(new java.awt.Color(255, 255, 255));
                    btnLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                    btnLogin.setForeground(new java.awt.Color(0, 0, 0));
                    btnLogin.setText("Login");
                    btnLogin.setBorder(null);
                    btnLogin.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        btnLoginActionPerformed(evt);
                              }
                    });

                    txtPassword.setBackground(new java.awt.Color(255, 255, 255));
                    txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                    txtPassword.setText("jPasswordField1");
                    txtPassword.setBorder(null);
                    txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
                              public void focusGained(java.awt.event.FocusEvent evt) {
                                        txtPasswordFocusGained(evt);
                              }
                    });

                    labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    labelLogo.setMaximumSize(new java.awt.Dimension(300, 175));
                    labelLogo.setMinimumSize(new java.awt.Dimension(300, 175));
                    labelLogo.setPreferredSize(new java.awt.Dimension(300, 175));

                    lblClose.setBackground(new java.awt.Color(255, 255, 255));
                    lblClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                    lblClose.setMaximumSize(new java.awt.Dimension(20, 20));
                    lblClose.setMinimumSize(new java.awt.Dimension(20, 20));
                    lblClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                              public void mouseMoved(java.awt.event.MouseEvent evt) {
                                        lblCloseMouseMoved(evt);
                              }
                    });
                    lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        lblCloseMouseClicked(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        lblCloseMouseExited(evt);
                              }
                    });

                    lblMinimizar.setMaximumSize(new java.awt.Dimension(20, 20));
                    lblMinimizar.setMinimumSize(new java.awt.Dimension(20, 20));
                    lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        lblMinimizarMouseClicked(evt);
                              }
                    });

                    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                    jPanel1.setLayout(jPanel1Layout);
                    jPanel1Layout.setHorizontalGroup(
                              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGap(86, 86, 86)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                      .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                                      .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                                      .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGap(112, 112, 112)
                                                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap(67, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                            .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addContainerGap())
                                                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(111, 111, 111))))
                    );
                    jPanel1Layout.setVerticalGroup(
                              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLogin)
                                        .addContainerGap(120, Short.MAX_VALUE))
                    );

                    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 374, 400));

                    pack();
          }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
              // TODO add your handling code here:
              
    }//GEN-LAST:event_txtUsuarioActionPerformed

          private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
                    // TODO add your handling code here:
                    txtUsuario.setText("");
          }//GEN-LAST:event_txtUsuarioMouseClicked

          private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
                    // TODO add your handling code here:
                    txtPassword.setText("");
          }//GEN-LAST:event_txtPasswordFocusGained

          private void lblCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseMoved
                    // TODO add your handling code here:
                    lblClose.setBackground(Color.red);
          }//GEN-LAST:event_lblCloseMouseMoved

          private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
                    // TODO add your handling code here:
                   
          }//GEN-LAST:event_lblCloseMouseExited

          private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
                    // TODO add your handling code here:
                    int dialog = JOptionPane.YES_NO_CANCEL_OPTION;
                    int result = JOptionPane.showConfirmDialog(null, "Desea salir?","Exit",dialog);
                    if(result==0){
                              System.exit(0);
                    }
          }//GEN-LAST:event_lblCloseMouseClicked

          private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
                    // TODO add your handling code here:
                    this.setState(LoginTordavi.ICONIFIED);
          }//GEN-LAST:event_lblMinimizarMouseClicked

          private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
                    // TODO add your handling code here:
                    validarLogin();
          }//GEN-LAST:event_btnLoginActionPerformed

          /**
           * @param args the command line arguments
           */
          public static void main(String args[]) {
                    /* Set the Nimbus look and feel */
                    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                     */
                    try {
                              for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                        if ("Nimbus".equals(info.getName())) {
                                                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                  break;
                                        }
                              }
                    } catch (ClassNotFoundException ex) {
                              java.util.logging.Logger.getLogger(LoginTordavi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                              java.util.logging.Logger.getLogger(LoginTordavi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                              java.util.logging.Logger.getLogger(LoginTordavi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                              java.util.logging.Logger.getLogger(LoginTordavi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    //</editor-fold>
                    //</editor-fold>

                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                              public void run() {
                                        new LoginTordavi().setVisible(true);
                              }
                    });
          }

          // Variables declaration - do not modify//GEN-BEGIN:variables
          private javax.swing.JButton btnLogin;
          private javax.swing.JPanel jPanel1;
          private javax.swing.JPanel jPanel2;
          private javax.swing.JSeparator jSeparator1;
          private javax.swing.JSeparator jSeparator2;
          private javax.swing.JLabel labelIncorrecto;
          private javax.swing.JLabel labelLogo;
          private javax.swing.JLabel lblClose;
          private javax.swing.JLabel lblMinimizar;
          private javax.swing.JPasswordField txtPassword;
          private javax.swing.JTextField txtUsuario;
          // End of variables declaration//GEN-END:variables
}
